Repository googleapis/synthtool, pull requests merged in 2018-11, with the labels that each got.

#116 Update github issue templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
Labels: cla: yes

#117 Drop the PR template for nodejs
  synthtool/gcp/templates/node_library/.github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#119 node: use latest npm for Windows
  synthtool/gcp/templates/node_library/.kokoro/test.bat
Labels: cla: yes

#120 Prefer https URLs for cloning from GitHub, add SYNTHTOOL_USE_SSH to use ssh
  synthtool/gcp/discogapic_generator.py
  synthtool/gcp/gapic_generator.py
  synthtool/sources/git.py
Labels: cla: yes

#121 Show stdout for docker pull
  synthtool/gcp/artman.py
  synthtool/shell.py
Labels: cla: yes

#122 Enable the autorelease reporter
  .kokoro/release.cfg
  .kokoro/release.sh
Labels: cla: yes

#123 Release synthtool 2018.11.08
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#125 Update eslintignore rules for nodejs
  synthtool/gcp/templates/node_library/.eslintignore
Labels: cla: yes

#127 Add basic metadata protos
  .flake8
  mypy.ini
  noxfile.py
  setup.py
  synthtool/protos/__init__.py
  synthtool/protos/metadata.proto
  synthtool/protos/metadata_pb2.py
  tests/test_metadata_protos.py
Labels: cla: yes

#129 Harden replace
  synthtool/transforms.py
Labels: cla: yes

#132 Add metadata reporting for Git sources.
  .coveragerc
  noxfile.py
  synthtool/__main__.py
  synthtool/metadata.py
  synthtool/sources/git.py
  tests/test_git.py
  tests/test_metadata.py
Labels: cla: yes

#135 Construct the artman instance only once.
  synthtool/gcp/gapic_generator.py
Labels: cla: yes

#136 Report Artman info to metadata
  synthtool/gcp/artman.py
  synthtool/metadata.py
  synthtool/protos/metadata.proto
  synthtool/protos/metadata_pb2.py
  tests/test_metadata.py
Labels: cla: yes

#140 Lazily clone googleapis{-private}
  synthtool/__main__.py
  synthtool/gcp/gapic_generator.py
Labels: cla: yes

#131 Add initial python templates
  synthtool/gcp/common.py
  synthtool/gcp/templates/python_library/.flake8
  synthtool/gcp/templates/python_library/MANIFEST.in
  synthtool/gcp/templates/python_library/setup.cfg
Labels: cla: yes

#141 Add option to change metadata output location
  synthtool/__main__.py
  synthtool/metadata.py
Labels: cla: yes

#142 Warn when running the synthesis script directly
  synthtool/__init__.py
Labels: cla: yes

#144 add noxfile template
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes

#145 Add ability to format java code with a custom google-java-format version
  synthtool/languages/java.py
Labels: cla: yes

#147 Release synthtool 2018.11.27
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#146 Update python templates
  synthtool/gcp/templates/python_library/.coveragerc
  synthtool/gcp/templates/python_library/.flake8
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes

#148 Release synthtool 2018.11.28
  CHANGELOG.md
  setup.py
Labels: autorelease: pending

#149 Report GCP common templates to metadata
  synthtool/__main__.py
  synthtool/gcp/common.py
  synthtool/metadata.py
Labels: cla: yes

#150 Fix private googleapis cloning
  synthtool/gcp/gapic_generator.py
Labels: cla: yes

#152 Release synthtool 2018.11.29
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#153 modify exclusion of local deps to not match folder name of repo
  synthtool/gcp/templates/python_library/.coveragerc
Labels: cla: yes

#156 Write update_time to metadata
  synthtool/metadata.py
  tests/test_metadata.py
Labels: cla: yes

#155 Report gapic generation to metadata
  synthtool/gcp/gapic_generator.py
  synthtool/metadata.py
  synthtool/protos/metadata.proto
  synthtool/protos/metadata_pb2.py
  tests/test_metadata.py
Labels: cla: yes

#157 Use 3.6 to run black as our as autosynth uses 3.6
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes

#158 Release synthtool 2018.11.30
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#159 fix: pass -md option to openssl
  synthtool/gcp/templates/node_library/.circleci/config.yml
Labels: cla: yes
