Repository googleapis/synthtool, pull requests merged in 2019-04, with the labels that each got.

#214 feat: also generate samples/README.md
  synthtool/gcp/common.py
  synthtool/gcp/templates/node_library/README.md
  synthtool/gcp/templates/node_library/samples/README.md
  synthtool/sources/templates.py
  tests/test_templates.py
Labels: cla: yes

#218 docs: copy in samples/README.md read poorly
  synthtool/gcp/templates/node_library/samples/README.md
Labels: cla: yes

#220 fix: support consecutive capital letters
  synthtool/__main__.py
  synthtool/gcp/common.py
  tests/test_common.py
Labels: cla: yes

#221 Release synthtool 2019.04.10
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#224 feat: Add `generator_args` arg to populate `--generator-args` artman option
  synthtool/gcp/artman.py
  synthtool/gcp/gapic_generator.py
Labels: cla: yes

#222 fix: None was printing in samples/README if introduction missing
  synthtool/gcp/templates/node_library/samples/README.md
Labels: cla: yes

#202 Add docs session to noxfile
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: :rotating_light:, cla: yes

#225 ruby: add AUTHENTICATION.md template
  synthtool/gcp/common.py
  synthtool/gcp/templates/ruby_library/AUTHENTICATION.md
  tests/test_templates.py
Labels: cla: yes

#227 Add `shutil` import to python noxfile template.
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes

#228 Update noxfile.py template.
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes

#229 feat: provide 'title' in .readme-partials.yaml to override the default
  synthtool/gcp/common.py
  synthtool/gcp/templates/node_library/README.md
  synthtool/gcp/templates/node_library/samples/README.md
Labels: cla: yes

#230 feat: add support for metadata comments in samples
  synthtool/gcp/common.py
  synthtool/gcp/templates/node_library/README.md
  synthtool/gcp/templates/node_library/samples/README.md
  synthtool/sources/templates.py
  tests/fixtures/samples/meta1.js
  tests/fixtures/samples/meta2.js
  tests/test_templates.py
Labels: cla: yes

#232 Fix move excludes
  synthtool/transforms.py
  tests/test_transforms.py
Labels: cla: yes

#226 feat: rework .nycrc to support --all
  synthtool/gcp/templates/node_library/.nycrc
Labels: :rotating_light:, cla: yes
