Repository googleapis/synthtool, pull requests merged in 2019-01, with the labels that each got.

#177 Add include_protos option to generation
  synthtool/gcp/gapic_generator.py
Labels: cla: yes

#178 node: update jsdoc templates
  synthtool/gcp/templates/node_library/.jsdoc.js
  synthtool/gcp/templates/node_library/.kokoro/docs.sh
Labels: cla: yes

#180 Release synthtool 2019.01.16
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#183 Ignore lint error about loader
  synthtool/__main__.py
Labels: cla: yes, kokoro:force-run

#179 node: ignore googleapis.com links
  synthtool/gcp/templates/node_library/.kokoro/docs.sh
Labels: cla: yes

#182 Update readme to latest instructions
  README.md
Labels: cla: yes

#184 Add special handling for Python to place protos next to protoc outputs
  synthtool/gcp/gapic_generator.py
Labels: cla: yes
