Repository googleapis/synthtool, pull requests merged in 2020-03, with the labels that each got.

#429 feat: add required option to s.copy()
  synthtool/languages/java.py
  synthtool/transforms.py
  tests/test_transforms.py
Labels: cla: yes

#428 build(nodejs-tests): adds support for build-cop and fixes coverage
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
  synthtool/gcp/templates/node_library/.kokoro/samples-test.sh
  synthtool/gcp/templates/node_library/.kokoro/system-test.sh
  synthtool/gcp/templates/node_library/.kokoro/test.sh
  synthtool/gcp/templates/node_library/.mocharc.js
Labels: cla: yes

#434 fix(java): relax regex for grpc header fix
  synthtool/languages/java.py
Labels: cla: yes

#437 test: add test for generating common java templates
  tests/fixtures/java_templates/standard/.repo-metadata.json
  tests/test_language_java.py
Labels: cla: yes

#439 chore(java): remove unused propose_release and bump_snapshot scripts
  synthtool/gcp/templates/java_library/.kokoro/continuous/propose_release.sh
  synthtool/gcp/templates/java_library/.kokoro/release/bump_snapshot.sh
Labels: cla: yes

#441 fix(java): update pull request template
  synthtool/gcp/templates/java_library/.github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#440 fix(java): set only renovate-bot as a trusted contributor
  synthtool/gcp/templates/java_library/.github/trusted-contribution.yml
Labels: cla: yes

#430 feat(java_templates): add sample pom files
  synthtool/gcp/templates/java_library/samples/install-without-bom/pom.xml
  synthtool/gcp/templates/java_library/samples/pom.xml
  synthtool/gcp/templates/java_library/samples/snapshot/pom.xml
  synthtool/gcp/templates/java_library/samples/snippets/pom.xml
  synthtool/languages/java.py
Labels: automerge, cla: yes

#444 fix(java): fix duplicated artifact in the reactor
  synthtool/gcp/templates/java_library/samples/install-without-bom/pom.xml
  synthtool/gcp/templates/java_library/samples/snapshot/pom.xml
Labels: cla: yes

#443 test(java): ensure generated pom.xml files are valid XML
  tests/test_language_java.py
Labels: cla: yes

#445 feat: track templates as git clone
  README.md
  synthtool/gcp/common.py
Labels: cla: yes

#433 docs: improve discoverability of how to edit this file
  synthtool/gcp/templates/node_library/README.md
Labels: cla: yes

#447 fix(java): fix snippet region tag
  synthtool/gcp/templates/java_library/samples/install-without-bom/pom.xml
Labels: cla: yes

#448 fix: joining / fails for string type
  synthtool/gcp/common.py
Labels: cla: yes

#446 docs: slight tweak to wording of contributing blurb in README
  synthtool/gcp/templates/node_library/README.md
Labels: cla: yes, do not merge

#449 fix(snippets): trim leading whitespace when extracting snippets
  synthtool/gcp/snippets.py
  tests/test_snippets.py
Labels: cla: yes

#451 build: use checkout@v2, not v1, as this allows manual re-running of tests
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
Labels: cla: yes, do not merge

#454 docs: document the release schedule we follow
  synthtool/gcp/templates/node_library/README.md
Labels: cla: yes

#453 fix(java): run mvn install with retry
  synthtool/gcp/templates/java_library/.kokoro/build.sh
  synthtool/gcp/templates/java_library/.kokoro/common.sh
  synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
  synthtool/gcp/templates/java_library/.kokoro/linkage-monitor.sh
Labels: cla: yes

#452 chore(java_templates): mark version bumps of current library as a chore
  synthtool/gcp/templates/java_library/renovate.json
  synthtool/languages/java.py
Labels: automerge, cla: yes

#456 fix: do not run node 8 CI
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
Labels: cla: yes

#457 chore(java): treat samples shared configuration dependency update as chore
  synthtool/gcp/templates/java_library/renovate.json
Labels: cla: yes

#458 chore(python): add license headers to config files; make small template edits
  synthtool/gcp/templates/python_library/.coveragerc
  synthtool/gcp/templates/python_library/.flake8
  synthtool/gcp/templates/python_library/.github/ISSUE_TEMPLATE/bug_report.md
  synthtool/gcp/templates/python_library/CONTRIBUTING.rst
  synthtool/gcp/templates/python_library/MANIFEST.in
  synthtool/gcp/templates/python_library/setup.cfg
Labels: cla: yes

#461 docs: remove "install stable" instructions
  README.md
Labels: cla: yes

#462 fix(ruby): remove dead troubleshooting link from generated auth guide
  synthtool/gcp/templates/ruby_library/AUTHENTICATION.md
Labels: cla: yes

#463 fix: update template files for Node.js libraries
  synthtool/gcp/templates/node_library/.eslintrc.json
  synthtool/gcp/templates/node_library/.eslintrc.yml
  synthtool/gcp/templates/node_library/.prettierrc
  synthtool/gcp/templates/node_library/.prettierrc.js
Labels: cla: yes, do not merge
