Repository googleapis/synthtool, pull requests merged in 2020-12, with the labels that each got.

#865 chore: add config / docs for 'pre-commit' support
  synthtool/gcp/templates/python_library/.pre-commit-config.yaml
  synthtool/gcp/templates/python_library/CONTRIBUTING.rst
Labels: cla: yes, lang: python

#859 test(python): give filesystem paths to pytest-cov
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: automerge, cla: yes

#868 fix: update noxfile.py.j2
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: cla: yes

#864 chore: Update publish_javadoc.sh
  synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc.sh
Labels: cla: yes

#830 feat(java): Add support for googleapis-discovery repository
  synthtool/gcp/gapic_bazel.py
  synthtool/languages/java.py
Labels: cla: yes

#873 fix(autosynth): apiary provider should include admin clients
  autosynth/providers/apiary.py
  tests/test_autosynth_apiary_provider.py
Labels: automerge, cla: yes

#874 chore(java): update trademark blurb in README
  synthtool/gcp/templates/java_library/README.md
Labels: automerge, cla: yes

#875 fix(python): always skip samples readmegen
  synthtool/languages/python.py
Labels: cla: yes, samples

#877 ci(java): ignore bot users for generate-files-bot
  synthtool/gcp/templates/java_library/.github/generated-files-bot.yml
Labels: automerge, cla: yes

#882 fix: Update apt before installing apt-transport-https
  .kokoro-autosynth/dotnet-build.sh
Labels: cla: yes

#880 docs(python): document adding Python 3.9 support, dropping 3.5 support
  synthtool/gcp/templates/python_library/CONTRIBUTING.rst
Labels: automerge, cla: yes

#872 docs: add instructions for authenticating for system tests
  synthtool/gcp/templates/node_library/CONTRIBUTING.md
  synthtool/gcp/templates/node_library/README.md
Labels: cla: yes

#885 chore: exclude `.nox` directories from linting
  synthtool/gcp/templates/python_library/.flake8
Labels: automerge, cla: yes

#886 fix: Don't create an observer unless tracking obsolete files
  synthtool/metadata.py
Labels: cla: yes

#888 feat: Update Ruby Apiary metadata path to match Repo reorganization
  autosynth/providers/ruby_apiary.py
Labels: cla: yes

#892 chore(java): remove formatter action
  synthtool/gcp/templates/java_library/.github/workflows/formatting.yaml
Labels: cla: yes
