Repository googleapis/synthtool, pull requests merged in 2020-06, with the labels that each got.

#597 fix: strip PR numbers from commit
  autosynth/git_source.py
  integration_tests/test_git_source.py
  tests/test_git_source.py
Labels: cla: yes

#598 feat: add "regenerate me" checkbox to pull requests
  autosynth/change_pusher.py
Labels: automerge, cla: yes

#588 chore(java_templates): add default CODEOWNERS files for samples reviews
  synthtool/gcp/templates/java_library/.github/CODEOWNERS
Labels: automerge, cla: yes

#589 doc: update and move READMEs
  README.md
  synthtool/README.md
Labels: cla: yes

#599 fix: update PR body after regenerating PR
  autosynth/change_pusher.py
  autosynth/github.py
Labels: cla: yes

#601 chore: turn on renovate-bot master issue for java repos
  synthtool/gcp/templates/java_library/renovate.json
Labels: cla: yes

#600 docs: improve README
  synthtool/README.md
Labels: cla: yes

#608 fix: decode output from individual synth run as utf-8 string
  autosynth/multi.py
  tests/test_multi.py
  tests/testdata/sponge-log-golden.xml
Labels: cla: yes

#609 fix: use 'logs' directory for base log path
  autosynth/multi.py
Labels: automerge, cla: yes

#603 build(java): skip lint on samples directory
  synthtool/gcp/templates/java_library/.kokoro/build.sh
Labels: automerge, cla: yes

#611 fix: switch back to using the PYTHONPATH statement
  synthtool/README.md
Labels: automerge, cla: yes

#610 fix: deep link into sponge2 which should contain the full output
  autosynth/multi.py
Labels: cla: yes

#575 feat: show output from microgenerator runs
  synthtool/gcp/gapic_microgenerator.py
Labels: cla: yes

#587 feat(secrets): begin migration to secret manager from keystore
  synthtool/gcp/templates/node_library/.kokoro/populate-secrets.sh
  synthtool/gcp/templates/node_library/.kokoro/publish.sh
  synthtool/gcp/templates/node_library/.kokoro/release/publish.cfg
  synthtool/gcp/templates/node_library/.kokoro/trampoline.sh
Labels: cla: yes

#613 fix: fix log path for single-commit, single-branch executions
  autosynth/synth.py
  autosynth/synthesizer.py
Labels: automerge, cla: yes

#614 fix: run tests and linters with py 3.8 too
  noxfile.py
Labels: cla: yes

#615 docs: add diagram and README for autosynth
  README.md
  autosynth/README.md
  images/flow.png
  synthtool/README.md
Labels: automerge, cla: yes

#618 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  synthtool/gcp/templates/node_library/.kokoro/populate-secrets.sh
Labels: cla: yes

#620 fix: use a [CHANGE ME] PR title when there's a commit without context
  autosynth/synth.py
  tests/test_synth.py
Labels: cla: yes

#622 doc: add a pydoc describing common transforms
  synthtool/README.md
  synthtool/pydoc.html
Labels: cla: yes

#624 feat: handle standardize START/END_EXCLUDE for snippets
  synthtool/gcp/snippets.py
  tests/fixtures/snippets/pom.xml
Labels: automerge, cla: yes

#625 ci(java): switch to secret manager from keystore
  synthtool/gcp/templates/java_library/.kokoro/build.sh
  synthtool/gcp/templates/java_library/.kokoro/nightly/samples.cfg
  synthtool/gcp/templates/java_library/.kokoro/populate-secrets.sh
  synthtool/gcp/templates/java_library/.kokoro/presubmit/samples.cfg
  synthtool/gcp/templates/java_library/.kokoro/trampoline.sh
Labels: cla: yes

#626 samples(java): fix bad character in samples.cfg from copy/paste
  synthtool/gcp/templates/java_library/.kokoro/nightly/samples.cfg
  synthtool/gcp/templates/java_library/.kokoro/presubmit/samples.cfg
Labels: automerge, cla: yes

#627 ci(java): switch integration test secrets to secret manager
  synthtool/gcp/templates/java_library/.kokoro/nightly/integration.cfg
  synthtool/gcp/templates/java_library/.kokoro/presubmit/integration.cfg
Labels: cla: yes

#628 ci(java): fix typo in java integration test secret name
  synthtool/gcp/templates/java_library/.kokoro/nightly/integration.cfg
  synthtool/gcp/templates/java_library/.kokoro/presubmit/integration.cfg
Labels: cla: yes

#582 fix: update node issue template
  synthtool/gcp/templates/node_library/.github/ISSUE_TEMPLATE/bug_report.md
Labels: cla: yes

#629 fix(python): change autodoc_default_flags to autodoc_default_options in python doc template
  synthtool/gcp/templates/python_library/docs/conf.py.j2
Labels: cla: yes

#631 fix: set default timeout to 5 hours
  .kokoro-autosynth/common.cfg
Labels: cla: yes

#630 docs: synthtool readme fixes for relative links
  synthtool/README.md
Labels: automerge, cla: yes

#633 ci(java): run dependency test on Java 8 and 11
  synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
  synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
Labels: cla: yes

#636 Revert "ci(java): run dependency test on Java 8 and 11 (#633)"
  synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
  synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
Labels: cla: yes

#637 feat: allow injecting template path as an argument
  synthtool/gcp/common.py
  synthtool/languages/java.py
  tests/test_language_java.py
Labels: cla: yes

#634 chore: assign code ownership of template directories to language teams
  CODEOWNERS
Labels: automerge, cla: yes

#640 fix: let failures to build from a single source fail fast
  autosynth/synth.py
  tests/test_synth.py
Labels: cla: yes

#639 ci(java): run dependency test on Java 8 and 11
  synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
  synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
  tests/test_language_java.py
Labels: automerge, cla: yes

#642 feat(python): add defaults for microgenerator libraries
  synthtool/gcp/common.py
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: automerge, cla: yes

#643 chore(python): fix line breaks in template and use newer black version
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes

#644 fix: leave a sponge_log.xml next to every sponge_log.log
  autosynth/multi.py
  autosynth/synth.py
  synthtool/report.py
  synthtool/report.xml.j2
  tests/test_multi.py
Labels: cla: yes

#646 Revert "build: install multiple Python versions for autosynth runs (#…
  .kokoro-autosynth/python-build.sh
  .kokoro-autosynth/python.cfg
Labels: cla: yes

#650 chore: use GOOGLE_CLOUD_PROJECT in samples noxfile
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: automerge, cla: yes, kokoro:force-run

#649 fix: remove all dependencies on sloth
  autosynth/github.py
  autosynth/multi.py
  autosynth/providers/java.py
  autosynth/providers/list_split_repositories.py
  autosynth/providers/nodejs.py
  autosynth/providers/python.py
  tests/test_github.py
Labels: cla: yes

#647 build: add config .gitattributes
  synthtool/gcp/templates/node_library/.gitattributes
  synthtool/gcp/templates/node_library/.kokoro/.gitattributes
Labels: cla: yes

#652 chore: update Py2 support msg to reflect passage of time
  synthtool/gcp/templates/python_library/docs/_templates/layout.html
Labels: cla: yes
