Repository googleapis/synthtool, pull requests merged in 2020-10, with the labels that each got.

#762 build(node_library): migrate to Trampoline V2
  synthtool/gcp/templates/node_library/.kokoro/common.cfg
  synthtool/gcp/templates/node_library/.kokoro/continuous/node10/common.cfg
  synthtool/gcp/templates/node_library/.kokoro/continuous/node12/common.cfg
  synthtool/gcp/templates/node_library/.kokoro/docs.sh
  synthtool/gcp/templates/node_library/.kokoro/lint.sh
  synthtool/gcp/templates/node_library/.kokoro/populate-secrets.sh
  synthtool/gcp/templates/node_library/.kokoro/presubmit/node10/common.cfg
  synthtool/gcp/templates/node_library/.kokoro/presubmit/node12/common.cfg
  synthtool/gcp/templates/node_library/.kokoro/publish.sh
  synthtool/gcp/templates/node_library/.kokoro/release/docs-devsite.cfg
  synthtool/gcp/templates/node_library/.kokoro/release/docs-devsite.sh
  synthtool/gcp/templates/node_library/.kokoro/release/docs.cfg
  synthtool/gcp/templates/node_library/.kokoro/release/docs.sh
  synthtool/gcp/templates/node_library/.kokoro/release/publish.cfg
  synthtool/gcp/templates/node_library/.kokoro/samples-test.sh
  synthtool/gcp/templates/node_library/.kokoro/system-test.sh
  synthtool/gcp/templates/node_library/.kokoro/test.sh
  synthtool/gcp/templates/node_library/.kokoro/trampoline.sh
  synthtool/gcp/templates/node_library/.kokoro/trampoline_v2.sh
  synthtool/gcp/templates/node_library/.trampolinerc
Labels: cla: yes

#784 fix: set the file mode for template file permissions when merging a file
  synthtool/transforms.py
  tests/fixtures/executable_file.sh
  tests/test_transforms.py
Labels: automerge, cla: yes

#788 fix(java-templates): custom templates needs to load partial metadata
  synthtool/gcp/common.py
  synthtool/gcp/partials.py
  synthtool/languages/java.py
  tests/test_partials.py
  tests/test_templates.py
Labels: cla: yes

#795 chore(python): use 'setup.py' to detect repo root
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: cla: yes

#729 docs: add synth instructions for pysamples
  synthtool/README.md
  synthtool/py_templating_instructions/.repo-metadata-template.json
  synthtool/py_templating_instructions/README.md
  synthtool/py_templating_instructions/synth-template.py
Labels: api: docs, cla: yes, samples

#800 build: grant push permissions to yoshi-* teams
  .github/sync-repo-settings.yaml
Labels: cla: yes

#801 fix: load flags from the specified synth.py file
  autosynth/synth.py
Labels: cla: yes

#798 build(java): remove release-please version tags from README
  synthtool/gcp/templates/java_library/README.md
Labels: cla: yes

#797 ci(java): suggest formatting fixes
  synthtool/gcp/templates/java_library/.github/workflows/formatting.yaml
Labels: automerge, cla: yes

#803 fix: samples tests should pass if no samples exist
  synthtool/gcp/templates/python_library/.kokoro/test-samples.sh
Labels: cla: yes

#804 ci(java): restrict presubmit samples ITs to only snapshot
  synthtool/gcp/templates/java_library/.kokoro/build.sh
Labels: automerge, cla: yes

#805 refactor: move some code from synth.py to synth_toolbox.py
  autosynth/change_pusher.py
  autosynth/git_source.py
  autosynth/multi.py
  autosynth/synth.py
  autosynth/synth_toolbox.py
  synthtool/gcp/gapic_bazel.py
  tests/test_synth.py
  tests/test_synth_toolbox.py
  tests/util.py
Labels: cla: yes

#789 build(java): auto-approve README regeneration
  synthtool/gcp/templates/java_library/.github/workflows/approve-readme.yaml
Labels: automerge, cla: yes

#810 build: only check --engine-strict for production deps
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
Labels: cla: yes

#809 docs: warn readers to not lint manually-written code in synth.py
  synthtool/README.md
Labels: cla: yes

#786 chore(python_library): change the docs bucket name
  synthtool/gcp/templates/python_library/.kokoro/docs/common.cfg
Labels: automerge, cla: yes

#802 feat: Configure Ruby Apiary autosynth job
  .kokoro-autosynth/ruby-apiary.cfg
  autosynth/multi.py
  autosynth/providers/ruby_apiary.py
Labels: cla: yes

#814 fix: Use a non-flag arg for the ruby-apiary-clean synth job
  autosynth/providers/ruby_apiary.py
Labels: cla: yes

#817 chore: remove `*` from owned dirs
  .github/CODEOWNERS
Labels: automerge, cla: yes

#818 build(java): enable snippet-bot
  synthtool/gcp/templates/java_library/.github/snippet-bot.yml
Labels: cla: yes

#821 chore: clean up and update renovate.json
  synthtool/gcp/templates/java_library/renovate.json
Labels: cla: yes

#790 chore: clean up Node.js TOC for cloud-rad
  synthtool/gcp/templates/node_library/.kokoro/release/docs-devsite.sh
Labels: automerge, cla: yes

#822 chore: fix Node.js TOC for cloud-rad
  synthtool/gcp/templates/node_library/.kokoro/release/docs-devsite.sh
Labels: cla: yes

#819 fix(java_library): Update publish_javadoc.sh
  synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc.sh
Labels: cla: yes

#808 chore(docs): update code of conduct of synthtool and templates
  CODE_OF_CONDUCT.md
  synthtool/gcp/templates/java_library/CODE_OF_CONDUCT.md
  synthtool/gcp/templates/node_library/CODE_OF_CONDUCT.md
  synthtool/gcp/templates/python_library/CODE_OF_CONDUCT.md
Labels: automerge, cla: yes

#825 build(node): update testing matrix
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
Labels: cla: yes

#820 docs: synthtool runs on Linux only
  synthtool/README.md
Labels: automerge, cla: yes

#827 build(node): don't run prepare during smoke test
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
Labels: cla: yes

#829 build(node): cleanup production deps before installing dev/production
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
Labels: cla: yes

#826 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  synthtool/gcp/templates/java_library/.kokoro/build.sh
Labels: automerge, cla: yes

#811 fix(python_library): fix unit test dependency installation
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: automerge, cla: yes

#832 docs: add proto-plus to intersphinx mapping
  synthtool/gcp/templates/python_library/docs/conf.py.j2
Labels: cla: yes

#831 fix(python_library): fix external unit test dependencies
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: automerge, cla: yes

#833 chore(java): enable generated-files-bot
  synthtool/gcp/templates/java_library/.github/generated-files-bot.yml
Labels: automerge, cla: yes
