Repository googleapis/synthtool, pull requests merged in 2020-11, with the labels that each got.

#834 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  synthtool/gcp/templates/node_library/.kokoro/trampoline_v2.sh
Labels: cla: yes

#837 chore(java_library): use production staging bucket
  synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc.cfg
Labels: cla: yes

#840 chore: add type hint check
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: cla: yes, lang: python

#841 fix: export clients as both const and type
  synthtool/gcp/templates/node_split_library/index.ts.j2
  tests/fixtures/node_templates/index_samples/sample_index.ts
  tests/fixtures/node_templates/index_samples/src/index.ts
Labels: cla: yes

#842 chore: add blacken to template
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: cla: yes

#843 chore(java): ignore return code 28 in README autosynth job
  synthtool/gcp/templates/java_library/.kokoro/readme.sh
Labels: cla: yes

#846 build(java): use code-suggester v1 tag rather than full semver
  synthtool/gcp/templates/java_library/.github/workflows/formatting.yaml
Labels: cla: yes

#847 fix: add blank line
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: cla: yes

#844 test(python): fix template defaults for noxfile default py versions
  synthtool/gcp/common.py
Labels: cla: yes

#854 build(java): use actions/github-script v3 tag rather than full semver
  synthtool/gcp/templates/java_library/.github/workflows/approve-readme.yaml
  synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
Labels: automerge, cla: yes

#855 feat: add kokoro config for PHP apiary
  .kokoro-autosynth/php-apiary.cfg
  .kokoro-autosynth/php-apiary.yaml
Labels: cla: yes

#856 docs(python): update intersphinx for grpc and auth
  synthtool/gcp/templates/python_library/docs/conf.py.j2
Labels: cla: yes

#857 fix: add pr-title in php-apiary
  .kokoro-autosynth/php-apiary.yaml
Labels: cla: yes

#860 docs(python): fix intersphinx link for google-auth
  synthtool/gcp/templates/python_library/docs/conf.py.j2
Labels: cla: yes

#858 chore(java): retry staging portion of the release with backoff
  synthtool/gcp/templates/java_library/.kokoro/common.sh
  synthtool/gcp/templates/java_library/.kokoro/release/stage.sh
Labels: cla: yes

#861 chore: turn off obsolete file tracking for nodejs
  .kokoro-autosynth/nodejs-shard0.cfg
  .kokoro-autosynth/nodejs-shard1.cfg
  .kokoro-autosynth/nodejs-shard2.cfg
  .kokoro-autosynth/nodejs-shard3.cfg
  .kokoro-autosynth/nodejs-shard4.cfg
  .kokoro-autosynth/nodejs-shard5.cfg
  .kokoro-autosynth/nodejs-shard6.cfg
  .kokoro-autosynth/nodejs-shard7.cfg
  .kokoro-autosynth/nodejs-shard8.cfg
  .kokoro-autosynth/nodejs-shard9.cfg
Labels: cla: yes

#862 build(java): enable blunderbuss for samples
  synthtool/gcp/templates/java_library/.github/blunderbuss.yml
Labels: cla: yes, samples

#852 docs: correct spelling of "targetting"
  synthtool/gcp/templates/node_library/README.md
Labels: cla: yes

#863 fix: truncate new PR titles at 250 characters
  autosynth/change_pusher.py
Labels: cla: yes
