Repository googleapis/synthtool, pull requests merged in 2020-09, with the labels that each got.

#742 chore(py-library): enable snippet-bot
  synthtool/gcp/templates/python_library/.github/snippet-bot.yml
Labels: cla: yes

#746 feat(python_samples): add in show_help functionality
  synthtool/gcp/common.py
  synthtool/gcp/templates/python_samples/README.md
  tests/generationmock/multiple_override_path/.repo-metadata.json
  tests/generationmock/multiple_override_path/override/quickstart.py
  tests/test_common.py
Labels: cla: yes

#750 fix: pin setuptools to 49.6.0
  requirements.txt
Labels: cla: yes

#752 chore: add static title for Go discovery regen
  .kokoro-autosynth/go-apiary.yaml
Labels: cla: yes

#745 chore(py-library): update decrypt secrets file
  synthtool/gcp/templates/python_library/scripts/decrypt-secrets.sh
Labels: cla: yes

#753 chore(python-library): use sphinx 1.5.5 for the docfx job
  synthtool/gcp/templates/python_library/docs/conf.py.j2
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes

#755 fix: don't attempt to create redundant PR to start tracking obsolete …
  autosynth/synth.py
Labels: cla: yes

#717 build(test): recursively find test files; fail on unsupported dependency versions
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
  synthtool/gcp/templates/node_library/.mocharc.js
Labels: api: cloudbuild, cla: yes, do not merge

#758 build(python): use release-publish app for notifying GitHub of releas…
  synthtool/gcp/templates/python_library/.kokoro/release/common.cfg
Labels: cla: yes

#759 build(python): add secret manager
  synthtool/gcp/templates/python_library/.kokoro/populate-secrets.sh
  synthtool/gcp/templates/python_library/.kokoro/trampoline.sh
Labels: cla: yes

#764 chore(java): set yoshi-java as default CODEOWNER
  synthtool/gcp/templates/java_library/.github/CODEOWNERS
Labels: cla: yes

#765 chore(python): add sphinx doctest extension
  synthtool/gcp/templates/python_library/docs/conf.py.j2
Labels: cla: yes

#763 chore: move codeowners and repo settings config
  .github/CODEOWNERS
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#766 chore(python): use sys.executable for sample readmegen
  synthtool/languages/python.py
Labels: cla: yes

#769 chore(python): remove note about editable installs
  synthtool/gcp/templates/python_library/CONTRIBUTING.rst
Labels: cla: yes

#770 chore: replace "sanity" with "confidence."
  synthtool/gcp/gapic_bazel.py
  synthtool/gcp/gapic_microgenerator.py
Labels: cla: yes

#771 chore(python): skip reporting coverage for namespace package
  synthtool/gcp/templates/python_library/.coveragerc
Labels: cla: yes

#772 build(java): use yoshi-approver token for auto-approve
  synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
Labels: cla: yes

#775 chore(ci): skip autorelease workflow on non-release PRs
  synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
Labels: cla: yes

#776 chore(ci): verify autorelease release PR content
  synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
Labels: cla: yes

#767 chore(java): use separate autosynth job for README
  autosynth/synth.py
  synthtool/gcp/common.py
  synthtool/gcp/templates/java_library/.github/readme/synth.py
  synthtool/gcp/templates/java_library/.kokoro/continuous/readme.cfg
  synthtool/gcp/templates/java_library/.kokoro/readme.sh
  synthtool/languages/java.py
  tests/test_language_java.py
Labels: automerge, cla: yes

#780 chore: update bucket for cloud-rad
  synthtool/gcp/templates/node_library/.kokoro/release/docs-devsite.sh
Labels: automerge, cla: yes

#778 chore(python): use BUILD_SPECIFIC_GCLOUD_PROJECT for samples
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.6/common.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.7/common.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.8/common.cfg
Labels: automerge, cla: yes, samples

#781 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  synthtool/gcp/templates/java_library/.github/workflows/samples.yaml
Labels: automerge, cla: yes

#782 build(java): readme.sh should be executable
  synthtool/gcp/templates/java_library/.kokoro/readme.sh
Labels: automerge, cla: yes
