Repository googleapis/synthtool, pull requests merged in 2020-08, with the labels that each got.

#695 feat(python_samples): Custom path for generation
  synthtool/gcp/common.py
  tests/generationmock/client_library/.repo-metadata.json
  tests/generationmock/client_library/samples/placeholder.txt
  tests/generationmock/custom_path/.repo-metadata.json
  tests/generationmock/custom_path/custom_samples_folder/placeholder.txt
  tests/generationmock/custom_path_DNE/.repo-metadata.json
  tests/generationmock/samples_folder/.repo-metadata.json
  tests/test_common.py
  tests/test_git.py
Labels: automerge, cla: yes

#713 chore(py_library): add some excludes in docs/conf.py
  synthtool/gcp/templates/python_library/docs/conf.py.j2
Labels: cla: yes

#709 feat: when obsolete file tracking gets flipped on, and there are no c…
  autosynth/git.py
  autosynth/synth.py
  tests/test_synth.py
Labels: cla: yes

#693 docs: recommend installation via pip -e
  synthtool/README.md
Labels: cla: yes

#692 cleanup: removes unused kokoro config files
  synthtool/gcp/templates/java_library/.kokoro/continuous/dependencies.cfg
  synthtool/gcp/templates/java_library/.kokoro/continuous/integration.cfg
  synthtool/gcp/templates/java_library/.kokoro/continuous/java11.cfg
  synthtool/gcp/templates/java_library/.kokoro/continuous/java7.cfg
  synthtool/gcp/templates/java_library/.kokoro/continuous/java8-osx.cfg
  synthtool/gcp/templates/java_library/.kokoro/continuous/java8-win.cfg
  synthtool/gcp/templates/java_library/.kokoro/continuous/lint.cfg
  synthtool/gcp/templates/java_library/.kokoro/continuous/propose_release.cfg
  synthtool/gcp/templates/java_library/.kokoro/continuous/samples.cfg
  synthtool/gcp/templates/java_library/.kokoro/nightly/dependencies.cfg
  synthtool/gcp/templates/java_library/.kokoro/nightly/lint.cfg
Labels: cla: yes

#678 build: update dependencies check to only check for runtime and compile scopes
  synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
Labels: cla: yes

#714 fix: don't remove obsolete file if it matches excludes pattern
  synthtool/metadata.py
  synthtool/transforms.py
  tests/test_metadata.py
Labels: cla: yes

#715 fix: don't remove obsolete files when synth raises exception
  synthtool/metadata.py
  tests/test_metadata.py
Labels: cla: yes

#632 build: --credential-file-override is no longer required
  synthtool/gcp/templates/node_library/.kokoro/populate-secrets.sh
Labels: automerge, cla: yes

#718 fix: snippet generation with start and end tags within excludes
  synthtool/gcp/snippets.py
  tests/fixtures/snippets/interleaved_with_exclude.js
  tests/test_snippets.py
Labels: cla: yes

#719 chore: update cloud rad kokoro build job
  synthtool/gcp/templates/node_library/.kokoro/release/docs-devsite.sh
Labels: cla: yes

#721 fix: reduce log level from DEBUG to INFO
  synthtool/log.py
Labels: cla: yes

#722 fix: really turn off verbose logging from watchdog
  synthtool/log.py
Labels: cla: yes

#723 build: perform publish using Node 12
  synthtool/gcp/templates/node_library/.kokoro/release/publish.cfg
Labels: cla: yes

#720 chore: enable obsolete file tracking for Ruby
  .kokoro-autosynth/ruby.cfg
Labels: cla: yes

#726 fix: Ensure watch_dir exists
  synthtool/metadata.py
  tests/test_metadata.py
Labels: cla: yes

#727 chore(java_templates): add lint/static analysis presubmit checks for samples
  synthtool/gcp/templates/java_library/.github/workflows/samples.yaml
Labels: cla: yes

#724 feat(python_samples): Allow for additional README generation in specified path(s)
  synthtool/gcp/common.py
  tests/generationmock/multiple_override_path/.repo-metadata.json
  tests/generationmock/multiple_override_path/override/placeholder.txt
  tests/generationmock/override_path/.repo-metadata.json
  tests/generationmock/override_path/override/placeholder.txt
  tests/test_common.py
Labels: cla: yes

#728 feat: enable obsolete file tracking for nodejs
  .kokoro-autosynth/nodejs.cfg
Labels: cla: yes

#730 chore(java_templates): stop running pmd/spotbugs checks for samples
  synthtool/gcp/templates/java_library/.github/workflows/samples.yaml
Labels: cla: yes

#732 fix(python_samples): README link fix, enforce samples=True
  synthtool/gcp/common.py
  synthtool/gcp/templates/python_samples/README.md
  tests/test_sample_templates.py
Labels: automerge, cla: yes

#725 fix: move system and samples test from Node 10 to Node 12
  synthtool/gcp/templates/node_library/.kokoro/continuous/node12/lint.cfg
  synthtool/gcp/templates/node_library/.kokoro/continuous/node12/samples-test.cfg
  synthtool/gcp/templates/node_library/.kokoro/continuous/node12/system-test.cfg
  synthtool/gcp/templates/node_library/.kokoro/presubmit/node12/samples-test.cfg
  synthtool/gcp/templates/node_library/.kokoro/presubmit/node12/system-test.cfg
Labels: cla: yes, do not merge

#733 fix: temporarily disable reporting to unblock releases
  synthtool/gcp/templates/java_library/.kokoro/release/stage.sh
Labels: cla: yes

#734 feat: shard lists of repos to synthesize
  .kokoro-autosynth/nodejs-shard0.cfg
  .kokoro-autosynth/nodejs-shard1.cfg
  .kokoro-autosynth/nodejs-shard2.cfg
  .kokoro-autosynth/nodejs-shard3.cfg
  .kokoro-autosynth/nodejs-shard4.cfg
  .kokoro-autosynth/nodejs-shard5.cfg
  .kokoro-autosynth/nodejs-shard6.cfg
  .kokoro-autosynth/nodejs-shard7.cfg
  .kokoro-autosynth/nodejs-shard8.cfg
  .kokoro-autosynth/nodejs-shard9.cfg
  autosynth/multi.py
  tests/test_multi.py
Labels: cla: yes

#738 fix: pin black lint tool version
  noxfile.py
Labels: cla: yes

#736 build: track flaky tests for "nightly", add new secrets for tagging
  synthtool/gcp/templates/node_library/.github/publish.yml
  synthtool/gcp/templates/node_library/.kokoro/release/publish.cfg
  synthtool/gcp/templates/node_library/.kokoro/samples-test.sh
  synthtool/gcp/templates/node_library/.kokoro/system-test.sh
  synthtool/gcp/templates/node_library/.kokoro/test.sh
Labels: cla: yes

#740 build(java): switch to release-publish app for notifying GitHub of release status
  synthtool/gcp/templates/java_library/.kokoro/release/stage.cfg
  synthtool/gcp/templates/java_library/.kokoro/release/stage.sh
Labels: automerge, cla: yes

#739 chore: enable obsolete file checking for python
  .kokoro-autosynth/python.cfg
Labels: cla: yes

#744 build: shard java autosynth builds
  .kokoro-autosynth/java-shard0.cfg
  .kokoro-autosynth/java-shard1.cfg
  .kokoro-autosynth/java-shard2.cfg
  .kokoro-autosynth/java-shard3.cfg
  .kokoro-autosynth/java-shard4.cfg
  .kokoro-autosynth/java-shard5.cfg
  .kokoro-autosynth/java-shard6.cfg
  .kokoro-autosynth/java-shard7.cfg
  .kokoro-autosynth/java-shard8.cfg
  .kokoro-autosynth/java-shard9.cfg
Labels: cla: yes

#741 chore: remove monolith nodejs autosynth
  .kokoro-autosynth/nodejs.cfg
Labels: cla: yes
