Repository googleapis/synthtool, pull requests merged in 2021-05, with the labels that each got.

#1064 build(java): switch to release-please for release tagging
  synthtool/gcp/templates/java_library/.github/release-please.yml
  synthtool/languages/java.py
  tests/fixtures/java_templates/release-please-update/.github/release-please.yml
  tests/fixtures/java_templates/release-please-update/.repo-metadata.json
  tests/test_language_java.py
Labels: cla: yes

#1048 chore: update CODEOWNERS for owlbot images
  .github/CODEOWNERS
Labels: cla: yes

#1063 build: use gapic-images/googleapis for PHP and Python builds
  .kokoro-autosynth/build-in-docker.sh
  .kokoro-autosynth/common.cfg
  .kokoro-autosynth/php.cfg
  .kokoro-autosynth/python-shard0.cfg
  .kokoro-autosynth/python-shard1.cfg
  .kokoro-autosynth/python-shard2.cfg
  .kokoro-autosynth/python-shard3.cfg
  .kokoro-autosynth/python-shard4.cfg
  .kokoro-autosynth/python-shard5.cfg
  .kokoro-autosynth/python-shard6.cfg
  .kokoro-autosynth/python-shard7.cfg
  .kokoro-autosynth/python-shard8.cfg
  .kokoro-autosynth/python-shard9.cfg
  .kokoro-autosynth/trampoline_v2.sh
  .trampolinerc
  autosynth/change_pusher.py
  autosynth/multi.py
  autosynth/synth.py
  autosynth/synthesizer.py
  docker/owlbot/python/Dockerfile
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes

#1067 chore: adding cloud-rad java xrefs
  synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc11.sh
Labels: cla: yes

#1073 fix(node): fetch default branch from env
  noxfile.py
  synthtool/gcp/common.py
  tests/test_common.py
Labels: cla: yes

#1075 fix: use google-gax v2.12.0
  docker/owlbot/nodejs/Dockerfile
Labels: cla: yes

#1076 build: remove codecov action
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
Labels: cla: yes

#1077 fix(Ruby): Use standard build script for Ruby jobs
  .kokoro-autosynth/ruby-build.sh
  .kokoro-autosynth/ruby.cfg
  synthtool/gcp/gapic_bazel.py
Labels: cla: yes

#1079 fix(deps): lock click to 7.x
  setup.py
Labels: cla: yes

#1078 build(java): remove codecov action
  synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
Labels: cla: yes

#1081 fix: broken rsync and end of kokoro build jobs
  .kokoro-autosynth/build.sh
Labels: cla: yes

#1082 chore: add changelog to cloud-rad
  synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc11.sh
Labels: cla: yes

#1080 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  synthtool/gcp/templates/java_library/.github/generated-files-bot.yml
  synthtool/gcp/templates/node_library/.github/generated-files-bot.yml
Labels: cla: yes

#1090 fix(owlbot-java): stop looking at synth.py files
  docker/owlbot/java/bin/write_templates.sh
  docker/owlbot/java/src/convert-synthtool-templates.py
Labels: cla: yes

#1087 fix: no default_version in .repo-metadata.json means no versions
  synthtool/languages/node.py
Labels: cla: yes

#1093 fix: don't invoke postprocess_gapic_library_hermetic() when there are
  synthtool/languages/node.py
Labels: cla: yes

#1092 chore: dump maven version along with java
  synthtool/gcp/templates/java_library/.kokoro/build.sh
Labels: automerge, cla: yes

#1089 build(python): use pinned sphinx version on docs
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes, lang: python

#1096 feat: add pip version override to python samples noxfile
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: automerge, cla: yes, samples

#1098 docs(python): fix broken links in multiprocessing.rst
  synthtool/gcp/templates/python_library/docs/multiprocessing.rst
Labels: automerge, cla: yes

#1099 feat: record post-processor-changes.txt for nodejs docker image
  docker/owlbot/nodejs/Dockerfile
  docker/owlbot/nodejs/cloudbuild.yaml
Labels: cla: yes

#1101 chore(python): add protobuf to intersphinx mapping
  synthtool/gcp/templates/python_library/docs/conf.py.j2
Labels: automerge, cla: yes

#1104 fix: make `generate_index_ts()` deterministic
  synthtool/languages/node.py
Labels: cla: yes
