Repository googleapis/synthtool, pull requests merged in 2021-11, with the labels that each got.

#1271 chore: upgrade bazel version in autosynth to 4.2.1
  .kokoro-autosynth/build.sh
Labels: cla: yes, automerge

#1272 fix: Remove obsolete ruby-docker autosynth job
  .kokoro-autosynth/ruby-docker.cfg
  autosynth/providers/ruby_docker.py
Labels: cla: yes

#1268 chore(java): remove pin on Apache Maven 3.8.1 from github actions
  synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
Labels: cla: yes, automerge

#1275 chore(java): update ci.yaml
  synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
Labels: cla: yes

#1269 chore: cleanup cloud RAD generation
  synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc11.sh
Labels: cla: yes

#1278 chore: update jre to 11 for linter
  synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
Labels: cla: yes, automerge

#1279 chore(java): update dependency verstions in java templates
  docker/owlbot/java/templates/poms/bom_pom.xml.j2
  docker/owlbot/java/templates/poms/parent_pom.xml.j2
  docker/owlbot/java/tests/new-client/golden/google-cloud-foo-bom/pom.xml
  docker/owlbot/java/tests/new-client/golden/pom.xml
  docker/owlbot/java/tests/new-version/golden/google-cloud-foo-bom/pom.xml
  docker/owlbot/java/tests/new-version/golden/pom.xml
  docker/owlbot/java/tests/new-version/input/google-cloud-foo-bom/pom.xml
  docker/owlbot/java/tests/new-version/input/pom.xml
Labels: cla: yes

#1277 chore(python): detect when samples testing requires custom dockerfile
  synthtool/gcp/common.py
Labels: cla: yes, samples

#1276 chore(python): run blacken session for all directories with a noxfile
  synthtool/languages/python.py
Labels: cla: yes

#1201 chore(python): add .github/CODEOWNERS as a templated file
  synthtool/gcp/templates/python_library/.github/CODEOWNERS
Labels: cla: yes

#1281 chore: update minimum java version to java 8
  synthtool/languages/java.py
Labels: cla: yes, automerge

#1283 fix: Remove obsolete ruby autosynth job
  .kokoro-autosynth/ruby.cfg
  autosynth/providers/ruby.py
Labels: cla: yes

#1285 chore(python): include UPGRADING.rst if it exists
  synthtool/gcp/common.py
Labels: cla: yes

#1284 chore: remove enable-samples profile
  synthtool/gcp/templates/java_library/.kokoro/build.sh
  synthtool/gcp/templates/java_library/CONTRIBUTING.md
Labels: cla: yes, automerge, samples

#1288 deps: upgrade google-java-format to 1.13.0
  docker/owlbot/java/Dockerfile
  docker/owlbot/java/container_test.yaml
Labels: cla: yes

#1292 Revert "deps: upgrade google-java-format to 1.13.0"
  docker/owlbot/java/Dockerfile
  docker/owlbot/java/container_test.yaml
Labels: cla: yes

#1293 chore: keep beta version intact
  docker/owlbot/java/src/fix-poms.py
Labels: cla: yes
