Repository googleapis/synthtool, pull requests merged in 2021-10, with the labels that each got.

#1233 chore: use cov_level in `.coveragerc`
  synthtool/gcp/templates/python_library/.coveragerc
Labels: cla: yes

#1230 fix: log a warning and continue on invalid sample metadata yaml
  synthtool/gcp/samples.py
  tests/fixtures/node_templates/bad_metadata/samples/bad_metadata1.js
  tests/fixtures/node_templates/bad_metadata/samples/meta1.js
  tests/test_samples.py
Labels: cla: yes, samples

#1232 build: use trampoline_v2 for python samples and allow custom dockerfile
  synthtool/gcp/common.py
  synthtool/gcp/templates/python_library/.kokoro/samples/lint/common.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.6/common.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.6/periodic-head.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.6/periodic.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.7/common.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.7/periodic.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.8/common.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.8/periodic-head.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.8/periodic.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.9/common.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.9/periodic-head.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.9/periodic.cfg
  synthtool/gcp/templates/python_library/.kokoro/test-samples-against-head.sh
  synthtool/gcp/templates/python_library/.kokoro/test-samples.sh
  synthtool/gcp/templates/python_library/.trampolinerc
Labels: cla: yes, samples

#1235 ci: add unit tests under Python 3.10
  synthtool/gcp/common.py
Labels: cla: yes, automerge

#1239 chore(python): Add kokoro configs for python 3.10 samples testing
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.10/common.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.10/continuous.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.10/periodic-head.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.10/periodic.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.10/presubmit.cfg
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: cla: yes, samples

#1245 chore(python): include docs/UPGRADING.md in docs/index.rst if it exists
  synthtool/gcp/common.py
  synthtool/gcp/templates/python_library/docs/index.rst
Labels: cla: yes

#1248 chore(python): fix erroneous versions detected in detect_versions()
  synthtool/gcp/common.py
  synthtool/languages/python.py
  tests/test_common.py
Labels: cla: yes

#1263 chore(python): modify templated noxfile to support non-cloud APIs
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes
