Repository googleapis/synthtool, pull requests merged in 2021-08, with the labels that each got.

#1174 docs(nodejs): move branch references to main
  synthtool/gcp/templates/node_library/.github/generated-files-bot.yml
  synthtool/gcp/templates/node_library/.kokoro/continuous/node10/common.cfg
  synthtool/gcp/templates/node_library/.kokoro/continuous/node10/test.cfg
  synthtool/gcp/templates/node_library/.kokoro/presubmit/node10/common.cfg
  synthtool/gcp/templates/node_library/.kokoro/samples-test.sh
  synthtool/gcp/templates/node_library/.kokoro/system-test.sh
  synthtool/gcp/templates/node_library/.kokoro/test.sh
  synthtool/gcp/templates/node_library/README.md
Labels: cla: yes

#1176 chore: fix INSTALL_LIBRARY_FROM_SOURCE in noxfile.py
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: cla: yes, automerge

#1175 build(java): use ENABLE_FLAKYBOT env variable
  synthtool/gcp/templates/java_library/.kokoro/build.sh
  synthtool/gcp/templates/java_library/.kokoro/nightly/integration.cfg
  synthtool/gcp/templates/java_library/.kokoro/nightly/samples.cfg
Labels: cla: yes, automerge

#1173 chore: drop mention of Python 2.7 from templates
  synthtool/gcp/common.py
  synthtool/gcp/templates/python_library/noxfile.py.j2
  synthtool/gcp/templates/python_library/scripts/readme-gen/templates/install_deps.tmpl.rst
  synthtool/gcp/templates/python_samples/noxfile.py.j2
  synthtool/languages/python.py
Labels: cla: yes

#1181 chore: remove obsolete kokoro configs for nodejs autosynth
  .kokoro-autosynth/node-apiary.yaml
  .kokoro-autosynth/nodejs-apiary.cfg
  .kokoro-autosynth/nodejs-build.sh
  .kokoro-autosynth/nodejs-shard0.cfg
  .kokoro-autosynth/nodejs-shard1.cfg
  .kokoro-autosynth/nodejs-shard2.cfg
  .kokoro-autosynth/nodejs-shard3.cfg
  .kokoro-autosynth/nodejs-shard4.cfg
  .kokoro-autosynth/nodejs-shard5.cfg
  .kokoro-autosynth/nodejs-shard6.cfg
  .kokoro-autosynth/nodejs-shard7.cfg
  .kokoro-autosynth/nodejs-shard8.cfg
  .kokoro-autosynth/nodejs-shard9.cfg
Labels: cla: yes

#1177 feat(autosynth)!: support alternate default branch
  autosynth/change_pusher.py
  autosynth/github.py
  autosynth/providers/php.py
  autosynth/providers/ruby.py
  autosynth/providers/ruby_docker.py
  autosynth/synth.py
  integration_tests/util.py
  synthtool/sources/git.py
  tests/test_github.py
  tests/test_synth.py
  tests/util.py
Labels: cla: yes, automerge

#1183 chore: replace feat/fix with chore in post-processor-changes.txt for python
  docker/owlbot/python/cloudbuild.yaml
Labels: cla: yes, lang: python

#1191 chore: fix log.py from failing lint-3.6 check
  synthtool/log.py
Labels: cla: yes

#1192 chore: enable release-trigger bot
  synthtool/gcp/templates/java_library/.github/release-trigger.yml
Labels: cla: yes

#1197 chore(python): disable dependency dashboard
  synthtool/gcp/templates/python_library/renovate.json
Labels: cla: yes, lang: python

#1199 build(java): update renovate config to mark conformance tests as a te…
  synthtool/gcp/templates/java_library/renovate.json
Labels: cla: yes
