Repository googleapis/synthtool, pull requests merged in 2021-07, with the labels that each got.

#1148 chore: remove All rights reserved clause from java.header
  synthtool/gcp/templates/java_library/java.header
Labels: automerge, cla: yes, kokoro:force-run

#1149 fix(ruby): Disable multi-commits for Ruby bazel autosynth
  .kokoro-autosynth/ruby.cfg
Labels: cla: yes

#1152 chore(docs): update README.md to add java support policy
  synthtool/gcp/templates/java_library/README.md
Labels: automerge, cla: yes

#1153 build(python): exit with success status if no samples found
  synthtool/gcp/templates/python_library/.kokoro/test-samples-impl.sh
Labels: cla: yes, samples

#1155 build(python): remove python 3.7 from kokoro Dockerfile
  synthtool/gcp/templates/python_library/.kokoro/docker/docs/Dockerfile
  synthtool/gcp/templates/python_library/.kokoro/docker/docs/fetch_gpg_keys.sh
  tests/test_python_library.py
Labels: automerge, cla: yes

#1154 fix: owlbot post-processor should generate README
  synthtool/languages/java.py
Labels: automerge, cla: yes

#1156 chore: add dependencyDashboardLabels to renovate.json
  synthtool/gcp/templates/java_library/renovate.json
Labels: automerge, cla: yes

#1158 fix: sync `python_samples` black version with `python_library`
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: automerge, cla: yes, samples

#1159 feat: add Samples section to CONTRIBUTING.rst
  synthtool/gcp/templates/python_library/CONTRIBUTING.rst
Labels: cla: yes

#1160 chore: add preserve_gapic to java library generation options
  synthtool/languages/java.py
Labels: automerge, cla: yes

#1129 build: switch to release-please release tagging
  synthtool/gcp/templates/node_library/.github/release-please.yml
Labels: automerge, cla: yes

#1163 chore(docs): remove mention about samples README
  synthtool/gcp/templates/java_library/README.md
Labels: automerge, cla: yes, samples

#1164 fix: fix the deprecation formatting
  synthtool/languages/java.py
  tests/test_language_java.py
  tests/testdata/SampleDeprecateClass.java
  tests/testdata/SampleDeprecateMethodGolden.java
Labels: automerge, cla: yes

#1165 refactor: alternative of splitting into add_javadoc and annotate_method
  synthtool/languages/java.py
Labels: cla: yes

#1162 chore(java): add a method to copy a java method and rename it
  .gitignore
  synthtool/languages/java.py
  tests/test_language_java.py
  tests/testdata/SampleCopyMethodGolden.java
  tests/testdata/SampleDeprecateClass.java
  tests/testdata/SampleDeprecateMethodGolden.java
Labels: automerge, cla: yes

#1167 chore: fix kokoro config for samples
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.6/periodic-head.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.7/periodic-head.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.8/periodic-head.cfg
  synthtool/gcp/templates/python_library/.kokoro/samples/python3.9/periodic-head.cfg
Labels: automerge, cla: yes, samples

#1161 chore(docs): add Authorization section to Java README template
  synthtool/gcp/templates/java_library/README.md
Labels: automerge, cla: yes

#1168 chore: remove java 7 units check
  synthtool/gcp/templates/java_library/.github/sync-repo-settings.yaml
  synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
Labels: automerge, cla: yes

#1169 build: update auto-approve config for new validation
  synthtool/gcp/templates/node_library/.github/auto-approve.yml
Labels: cla: yes
