Repository googleapis/synthtool, pull requests merged in 2021-04, with the labels that each got.

#995 feat(bazel): Add clean_build option to synthtool
  autosynth/change_pusher.py
  autosynth/git.py
  autosynth/git_source.py
  autosynth/multi.py
  autosynth/providers/ruby_apiary.py
  autosynth/synth.py
  synthtool/gcp/gapic_bazel.py
Labels: automerge, cla: yes

#1015 fix(java): owlbot parent version should use existing parent version
  docker/owlbot/java/cloudbuild_test.yaml
  docker/owlbot/java/src/fix-poms.py
  docker/owlbot/java/tests/README.md
  docker/owlbot/java/tests/new-version/golden/.gitignore
  docker/owlbot/java/tests/new-version/golden/.repo-metadata.json
  docker/owlbot/java/tests/new-version/golden/google-cloud-foo-bom/pom.xml
  docker/owlbot/java/tests/new-version/golden/google-cloud-foo/pom.xml
  docker/owlbot/java/tests/new-version/golden/google-cloud-foo/src/main/java/com/google/cloud/foo/SomeServiceClient.java
  docker/owlbot/java/tests/new-version/golden/google-cloud-foo/src/main/java/com/google/cloud/foo/SomeServiceSettings.java
  docker/owlbot/java/tests/new-version/golden/grpc-google-cloud-foo-v1/pom.xml
  docker/owlbot/java/tests/new-version/golden/grpc-google-cloud-foo-v1/src/main/java/com/google/cloud/foo/SomeService.java
  docker/owlbot/java/tests/new-version/golden/grpc-google-cloud-foo-v2/pom.xml
  docker/owlbot/java/tests/new-version/golden/grpc-google-cloud-foo-v2/src/main/java/com/google/cloud/foo/v2/SomeService.java
  docker/owlbot/java/tests/new-version/golden/pom.xml
  docker/owlbot/java/tests/new-version/golden/proto-google-cloud-foo-v1/clirr-ignored-differences.xml
  docker/owlbot/java/tests/new-version/golden/proto-google-cloud-foo-v1/pom.xml
  docker/owlbot/java/tests/new-version/golden/proto-google-cloud-foo-v1/src/main/java/com/google/cloud/foo/SomeMessage.java
  docker/owlbot/java/tests/new-version/golden/proto-google-cloud-foo-v2/clirr-ignored-differences.xml
  docker/owlbot/java/tests/new-version/golden/proto-google-cloud-foo-v2/pom.xml
  docker/owlbot/java/tests/new-version/golden/proto-google-cloud-foo-v2/src/main/java/com/google/cloud/foo/v2/SomeMessage.java
  docker/owlbot/java/tests/new-version/golden/versions.txt
  docker/owlbot/java/tests/new-version/input/.gitignore
  docker/owlbot/java/tests/new-version/input/.repo-metadata.json
  docker/owlbot/java/tests/new-version/input/google-cloud-foo-bom/pom.xml
  docker/owlbot/java/tests/new-version/input/google-cloud-foo/pom.xml
  docker/owlbot/java/tests/new-version/input/google-cloud-foo/src/main/java/com/google/cloud/foo/SomeServiceClient.java
  docker/owlbot/java/tests/new-version/input/google-cloud-foo/src/main/java/com/google/cloud/foo/SomeServiceSettings.java
  docker/owlbot/java/tests/new-version/input/grpc-google-cloud-foo-v1/pom.xml
  docker/owlbot/java/tests/new-version/input/grpc-google-cloud-foo-v1/src/main/java/com/google/cloud/foo/SomeService.java
  docker/owlbot/java/tests/new-version/input/grpc-google-cloud-foo-v2/pom.xml
  docker/owlbot/java/tests/new-version/input/grpc-google-cloud-foo-v2/src/main/java/com/google/cloud/foo/v2/SomeService.java
  docker/owlbot/java/tests/new-version/input/pom.xml
  docker/owlbot/java/tests/new-version/input/proto-google-cloud-foo-v1/clirr-ignored-differences.xml
  docker/owlbot/java/tests/new-version/input/proto-google-cloud-foo-v1/pom.xml
  docker/owlbot/java/tests/new-version/input/proto-google-cloud-foo-v1/src/main/java/com/google/cloud/foo/SomeMessage.java
  docker/owlbot/java/tests/new-version/input/proto-google-cloud-foo-v2/src/main/java/com/google/cloud/foo/v2/SomeMessage.java
  docker/owlbot/java/tests/new-version/input/versions.txt
Labels: automerge, cla: yes

#1016 fix: non-root users can run the nodejs docker post processor
  docker/owlbot/nodejs/Dockerfile
  docker/owlbot/nodejs/entrypoint.sh
  docker/owlbot/python/Dockerfile
Labels: cla: yes

#1022 chore: Use python 3.6.13-buster for owlbot post-processor
  docker/owlbot/python/Dockerfile
Labels: cla: yes

#1021 chore: Add license headers for python config files
  synthtool/gcp/templates/python_library/.pre-commit-config.yaml
  synthtool/gcp/templates/python_library/docs/conf.py.j2
Labels: automerge, cla: yes

#1025 meta: add @googleapis/github-automation as owner
  .github/CODEOWNERS
Labels: cla: yes

#1024 feat: expose get_staging_dirs() for Python
  docker/owlbot/python/Dockerfile
  synthtool/__init__.py
  synthtool/languages/python.py
  synthtool/transforms.py
  tests/test_transforms.py
Labels: cla: yes

#1032 feat: add excludes and patch callback arguments to owlbot_main
  docker/owlbot/nodejs/Dockerfile
  synthtool/gcp/common.py
  synthtool/languages/node.py
  tests/fixtures/nodejs-dlp-with-staging/owl-bot-staging/v2/src/index.ts
  tests/fixtures/nodejs-dlp-with-staging/src/index.ts
  tests/test_node.py
Labels: cla: yes

#1028 chore: add deprecation warning template to readme
  synthtool/gcp/partials.py
  synthtool/gcp/templates/java_library/README.md
Labels: cla: yes

#1034 build(java): skip javadoc tests during dependencies test
  synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
Labels: cla: yes

#1035 chore: add sync-repo-settings.yaml file to java templates
  synthtool/gcp/templates/java_library/.github/sync-repo-settings.yaml
  synthtool/languages/java.py
Labels: cla: yes

#1036 chore: remove extra whitespaces from java README template
  synthtool/gcp/templates/java_library/README.md
Labels: automerge, cla: yes

#1012 chore: add constraints file check for python samples
  synthtool/gcp/templates/python_library/.github/header-checker-lint.yml
  synthtool/gcp/templates/python_library/renovate.json
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: automerge, cla: yes, samples

#1037 fix: typo
  synthtool/gcp/templates/java_library/.kokoro/build.sh
Labels: automerge, cla: yes

#1043 fix: release scripts from issuing overlapping phases
  synthtool/gcp/templates/java_library/.kokoro/release/snapshot.sh
  synthtool/gcp/templates/java_library/.kokoro/release/stage.sh
Labels: automerge, cla: yes

#1042 fix(owlbot-java): run owlbot.py if present
  docker/owlbot/java/bin/write_templates.sh
Labels: automerge, cla: yes

#1041 docs(python): insert empty lines between methods in generated docs
  synthtool/gcp/templates/python_library/docs/_static/custom.css
Labels: automerge, cla: yes

#1045 fix: get_staging_dirs default_version should be optional
  synthtool/transforms.py
  tests/fixtures/staging_dirs/owl-bot-staging/v1/.gitkeep
  tests/fixtures/staging_dirs/owl-bot-staging/v2/.gitkeep
  tests/test_transforms.py
Labels: automerge, cla: yes

#1040 build: use PyPI API token in secret manager
  synthtool/gcp/templates/python_library/.kokoro/release.sh
  synthtool/gcp/templates/python_library/.kokoro/release/common.cfg
Labels: automerge, cla: yes

#1047 fix(owlbot-java): run owlboy.py directly rather than via synthtool module
  docker/owlbot/java/bin/write_templates.sh
Labels: cla: yes

#1031 fix: Add fetch for default branch
  synthtool/gcp/common.py
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
  synthtool/gcp/templates/node_library/README.md
  synthtool/gcp/templates/node_library/samples/README.md
  tests/test_common.py
  tests/test_transforms.py
Labels: cla: yes

#1050 fix: get_staging_dirs() should return a consistent ordering
  synthtool/transforms.py
  tests/test_transforms.py
Labels: cla: yes

#1046 build(node): remove unused tokens
  synthtool/gcp/templates/node_library/.kokoro/release/publish.cfg
Labels: cla: yes

#1052 build(node): default-branch should use $default_branch
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
Labels: cla: yes

#1054 chore: Fix python owlbot post processor image cloudbuild.yaml
  docker/owlbot/python/cloudbuild.yaml
Labels: automerge, cla: yes

#1053 refactor(test): add util.chdir, util.copied_fixtures_dir contextmanagers to clean up tests
  tests/test_common.py
  tests/test_language_java.py
  tests/test_node.py
  tests/test_partials.py
  tests/test_python_library.py
  tests/test_samples.py
  tests/test_snippets.py
  tests/test_transforms.py
  tests/test_util.py
  tests/util.py
Labels: cla: yes

#1058 chore(python): remove noxfile.py check for GOOGLE_APPLICATION_CREDENTIALS
  synthtool/gcp/templates/python_library/CONTRIBUTING.rst
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes

#1051 fix: snippet parser should handle reused region tags
  synthtool/gcp/snippets.py
  tests/fixtures/snippets/reused.js
  tests/test_snippets.py
Labels: automerge, cla: yes

#1059 chore: ignore release-please.yml if it already exists
  synthtool/languages/java.py
Labels: automerge, cla: yes

#1061 build(node): Add `generate-files-bot` config
  synthtool/gcp/templates/node_library/.github/generated-files-bot.yml
Labels: cla: yes

#1060 build(node): switch $default-branch with template variable
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
Labels: cla: yes
