Repository googleapis/synthtool, pull requests merged in 2021-09, with the labels that each got.

#1200 chore(python): group renovate prs
  synthtool/gcp/templates/python_library/renovate.json
Labels: cla: yes

#1188 chore(python): rename default branch to main
  synthtool/gcp/templates/python_library/.kokoro/build.sh
  synthtool/gcp/templates/python_library/.kokoro/test-samples-impl.sh
  synthtool/gcp/templates/python_library/CONTRIBUTING.rst
  synthtool/gcp/templates/python_library/docs/conf.py.j2
Labels: cla: yes

#1202 chore(java): install maven 3.8.1 at runtime
  synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
Labels: cla: yes, automerge

#1205 chore(java): update windows build
  synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
Labels: cla: yes, automerge

#1203 feat: publish post-processor images to cloud-devrel-public-resources
  docker/owlbot/java/cloudbuild.yaml
  docker/owlbot/nodejs/cloudbuild.yaml
Labels: cla: yes

#1206 chore(java): remove readme autosynth job config
  synthtool/gcp/templates/java_library/.kokoro/continuous/readme.cfg
Labels: cla: yes, automerge

#1207 chore: remove readme synth.py config
  synthtool/gcp/templates/java_library/.github/readme/synth.py
Labels: cla: yes

#1208 chore: add gcf-owl-bot to list of trusted contributors
  synthtool/gcp/templates/java_library/.github/trusted-contribution.yml
Labels: cla: yes, automerge

#1182 chore(java): update shared-config and shared-dependencies version in pom template
  docker/owlbot/java/templates/poms/bom_pom.xml.j2
  docker/owlbot/java/templates/poms/parent_pom.xml.j2
  docker/owlbot/java/tests/new-client/golden/google-cloud-foo-bom/pom.xml
  docker/owlbot/java/tests/new-client/golden/pom.xml
  docker/owlbot/java/tests/new-version/golden/google-cloud-foo-bom/pom.xml
  docker/owlbot/java/tests/new-version/golden/pom.xml
  docker/owlbot/java/tests/new-version/input/google-cloud-foo-bom/pom.xml
  docker/owlbot/java/tests/new-version/input/pom.xml
  synthtool/gcp/templates/java_library/.kokoro/release/common.sh
  synthtool/gcp/templates/java_library/.kokoro/release/drop.sh
  synthtool/gcp/templates/java_library/.kokoro/release/promote.sh
  synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc.sh
  synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc11.sh
  synthtool/gcp/templates/java_library/.kokoro/release/stage.sh
  synthtool/gcp/templates/java_library/.kokoro/trampoline.sh
Labels: cla: yes, automerge

#1211 chore(java): don't mess with poms for non-client library repos
  docker/owlbot/java/src/fix-poms.py
Labels: cla: yes, automerge

#1212 build: enable release-trigger bot
  synthtool/gcp/templates/node_library/.github/release-trigger.yml
Labels: cla: yes

#1213 chore: google-cloud-python now uses 'main' for default branch
  synthtool/gcp/templates/python_samples/README.md
Labels: cla: yes

#1214 chore: blacken samples noxfile template
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: cla: yes, samples

#1218 build(owl-bot-java): don't crash if there are no clirr-ignore-difference.xml files
  docker/owlbot/java/bin/write_clirr_ignore.sh
Labels: cla: yes

#1219 fix: Remove now-invalid backend_type from Kokoro config files
  .kokoro-autosynth/common.cfg
  .kokoro/release.cfg
Labels: cla: yes

#1220 chore(java): remove dependencyDashboardLabel config from renovate.json
  synthtool/gcp/templates/java_library/renovate.json
Labels: cla: yes, automerge

#1221 chore(java): rename master branch to main
  synthtool/gcp/templates/java_library/.github/blunderbuss.yml
  synthtool/gcp/templates/java_library/.github/sync-repo-settings.yaml
  synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
  synthtool/gcp/templates/java_library/README.md
Labels: cla: yes, automerge

#1216 build: add jdk 17 to java units and dependency builds
  synthtool/gcp/templates/java_library/.github/workflows/ci.yaml
  synthtool/gcp/templates/java_library/.kokoro/dependencies.sh
Labels: cla: yes

#1226 build(nodejs): switch to linkinator for scanning links
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
Labels: cla: yes

#1227 build(node): run linkinator against index.html
  synthtool/gcp/templates/node_library/.github/workflows/ci.yaml
Labels: cla: yes

#1229 chore(java): fix release-please version replace tags for initial samples pom.xml
  synthtool/gcp/templates/java_library/samples/snapshot/pom.xml
Labels: cla: yes, samples

#1225 chore: fail samples nox session if python version is missing
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: cla: yes, samples
