Repository googleapis/synthtool, pull requests merged in 2021-03, with the labels that each got.

#964 chore: remove docLava v2 doc generation
  synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc.cfg
  synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc.sh
Labels: cla: yes

#965 test: install pyopenssl for mtls testing
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes

#969 chore: copy README to docfx-yml dir
  synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc11.sh
Labels: cla: yes

#970 build(node): lint system-test and test
  synthtool/languages/node.py
Labels: cla: yes

#973 fix(owl-bot): add script that reverts license year changes
  docker/owlbot/nodejs/entrypoint.sh
  docker/owlbot/nodejs/restore_license_headers.sh
Labels: cla: yes

#975 build: test docker publish pipeline
  docker/owlbot/nodejs/Dockerfile
Labels: cla: yes

#968 docs: explain what autosynth failure means and link to troubleshooting…
  autosynth/TroubleShooting.md
  autosynth/multi.py
Labels: cla: yes

#971 feat(node): add helper for detecting versions
  docker/owlbot/nodejs/Dockerfile
  synthtool/languages/node.py
  synthtool/protos/metadata_pb2.py
  synthtool/protos/preconfig_pb2.py
Labels: cla: yes

#979 Revert "fix(owl-bot): add script that reverts license year changes"
  docker/owlbot/nodejs/entrypoint.sh
  docker/owlbot/nodejs/restore_license_headers.sh
Labels: automerge, cla: yes

#977 build: shard python autosynth job
  .kokoro-autosynth/python-shard0.cfg
  .kokoro-autosynth/python-shard1.cfg
  .kokoro-autosynth/python-shard2.cfg
  .kokoro-autosynth/python-shard3.cfg
  .kokoro-autosynth/python-shard4.cfg
  .kokoro-autosynth/python-shard5.cfg
  .kokoro-autosynth/python-shard6.cfg
  .kokoro-autosynth/python-shard7.cfg
  .kokoro-autosynth/python-shard8.cfg
  .kokoro-autosynth/python-shard9.cfg
Labels: automerge, cla: yes

#980 build(java): update autorelease title check in response to the new multi release branch changes
  synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
Labels: automerge, cla: yes

#985 chore: add pre-commit-config to renovate ignore paths
  synthtool/gcp/templates/python_library/renovate.json
Labels: cla: yes

#982 build(python): fail nox sessions if a python version is missing
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: automerge, cla: yes

#987 feat(node): invoke owlbot_main() where there's no owlbot.py in the repo
  docker/owlbot/nodejs/entrypoint.sh
  synthtool/languages/node.py
Labels: cla: yes

#990 fix: lint all ts/js
  synthtool/languages/node.py
Labels: cla: yes

#993 fix: pass versions and default_versions to common_templates.node_library()
  synthtool/languages/node.py
Labels: cla: yes

#981 fix: tell the user autosynth may take 24 hours to regenerate
  autosynth/change_pusher.py
Labels: cla: yes

#869 test(python): use constraints files to check dependency lower bounds
  synthtool/gcp/templates/python_library/noxfile.py.j2
  tests/test_python_library.py
Labels: automerge, cla: yes

#998 chore(java): detect sample-secrets in build.sh
  synthtool/gcp/templates/java_library/.kokoro/build.sh
Labels: automerge, cla: yes, samples

#1001 chore: fix typo on troubleshooting.md
  autosynth/TroubleShooting.md
Labels: cla: yes

#999 chore: let snippet-bot ignore files under test/fixtures
  .github/snippet-bot.yml
Labels: cla: yes

#991 feat: add Java owl-bot post-processing image
  docker/owlbot/java/Dockerfile
  docker/owlbot/java/README.md
  docker/owlbot/java/bin/entrypoint.sh
  docker/owlbot/java/bin/format_source.sh
  docker/owlbot/java/bin/restore_license_headers.sh
  docker/owlbot/java/bin/write_clirr_ignore.sh
  docker/owlbot/java/bin/write_missing_pom_files.sh
  docker/owlbot/java/bin/write_templates.sh
  docker/owlbot/java/cloudbuild.yaml
  docker/owlbot/java/cloudbuild_test.yaml
  docker/owlbot/java/container_test.yaml
  docker/owlbot/java/src/convert-synthtool-templates.py
  docker/owlbot/java/src/fix-poms.py
  docker/owlbot/java/src/gen-template.py
  docker/owlbot/java/src/poms/module.py
  docker/owlbot/java/src/poms/templates.py
  docker/owlbot/java/src/requirements.txt
  docker/owlbot/java/templates/clirr/clirr-ignored-differences.xml.j2
  docker/owlbot/java/templates/gitignore
  docker/owlbot/java/templates/poms/bom_pom.xml.j2
  docker/owlbot/java/templates/poms/cloud_pom.xml.j2
  docker/owlbot/java/templates/poms/grpc_pom.xml.j2
  docker/owlbot/java/templates/poms/parent_pom.xml.j2
  docker/owlbot/java/templates/poms/proto_pom.xml.j2
  docker/owlbot/java/templates/poms/versions.txt.j2
Labels: automerge, cla: yes

#1006 chore: remove STAGING_BUCKET_V2 check
  synthtool/gcp/templates/java_library/.kokoro/release/publish_javadoc.sh
Labels: cla: yes

#1011 build(python): update docfx job to use new plugin
  synthtool/gcp/templates/python_library/noxfile.py.j2
Labels: cla: yes, lang: python

#1002 feat: an owl-bot docker image for python
  docker/owlbot/python/Dockerfile
  docker/owlbot/python/cloudbuild.yaml
  docker/owlbot/python/entrypoint.sh
  synthtool/languages/python.py
Labels: cla: yes

#1009 fix(owlbot-java): after copying code, fix the license headers
  docker/owlbot/java/bin/entrypoint.sh
  docker/owlbot/java/bin/fix_license_headers.sh
  docker/owlbot/java/src/fix-license-headers.py
Labels: cla: yes

#1008 fix(java): make license header fixing idempotent
  synthtool/languages/java.py
  tests/test_language_java.py
  tests/testdata/FooGrpcGolden.java
  tests/testdata/FooProtoGolden.java
  tests/testdata/src/foo/FooGrpc.java
  tests/testdata/src/foo/FooProto.java
Labels: automerge, cla: yes
