Repository googleapis/synthtool, pull requests merged in 2022-04, with the labels that each got.

#1223 chore(deps): disable dependency dashboard
  renovate.json
Labels: cla: yes

#1247 chore: add classifiers for python 3.7, 3.8 and 3.9
  setup.py
Labels: cla: yes

#1294 chore(python): refactor unit / system test dependency install
  synthtool/gcp/templates/python_library/noxfile.py.j2
  tests/test_python_library.py
Labels: cla: yes

#1352 fix: clarify the gax-nodejs usage in README
  synthtool/gcp/templates/node_library/README.md
Labels: api: automl

#1356 build(node): update client library version in samples metadata
  synthtool/languages/common.py
  synthtool/languages/node.py
  tests/fixtures/samples/generated/v1/snippet_metadata.google.cloud.asset.v1.json
  tests/fixtures/samples/generated/v2/snippet_metadata.google.cloud.asset.v2.json
  tests/test_languages_common.py
Labels: samples
