Repository googleapis/synthtool, pull requests merged in 2022-08, with the labels that each got.

#1518 feat(node-mono-repo): add release-please-config post-processing
  synthtool/languages/node_mono_repo.py
  tests/fixtures/node_templates/release_please/release-please-config-post.json
  tests/fixtures/node_templates/release_please/release-please-config.json
  tests/test_node_mono_repo.py
Labels: automerge: exact

#1524 fix(node-mono-repo): generate README and samples/README
  synthtool/gcp/common.py
  synthtool/languages/node_mono_repo.py
Labels: samples

#1527 feat(node_mono_repo): copy the list sample to a quickstart
  synthtool/languages/common.py
  synthtool/languages/node_mono_repo.py
  tests/fixtures/nodejs_mono_repo_with_samples/packages/datastore/samples/generated/compare_to_quickstart.js
  tests/fixtures/nodejs_mono_repo_with_samples/packages/datastore/samples/generated/v1/dataproc_metastore.create_backup.js
  tests/fixtures/nodejs_mono_repo_with_samples/packages/datastore/samples/generated/v1/dataproc_metastore.list_backups.js
  tests/fixtures/nodejs_mono_repo_with_samples/packages/datastore/samples/generated/v1/snippet_metadata.google.cloud.asset.v1.json
  tests/fixtures/nodejs_mono_repo_with_samples/packages/datastore/samples/generated/v2/snippet_metadata.google.cloud.asset.v2.json
  tests/test_node_mono_repo.py
Labels: samples

#1540 chore: remove release config and script
  .kokoro/release.cfg
  .kokoro/release.sh
Labels: automerge
