Repository googleapis/synthtool, pull requests merged in 2022-01, with the labels that each got.

#1301 fix(java): run Maven in plain console-friendly mode
  synthtool/gcp/templates/java_library/.kokoro/build.sh
Labels: automerge

#1316 chore: use python-samples-reviewers
  synthtool/gcp/templates/python_library/.github/CODEOWNERS
Labels: samples

#1320 chore(owlbot-java): disable re-writing clirr file in owlbot java post-processor
  docker/owlbot/java/bin/write_clirr_ignore.sh
Labels: automerge

#1321 chore: Add check for tests in directory
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: automerge

#1324 chore(python): fix undefined name 'glob' in samples noxfile
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: automerge, samples

#1085 chore: update github issue templates
  synthtool/gcp/templates/node_library/.github/ISSUE_TEMPLATE/bug_report.md
  synthtool/gcp/templates/node_library/.github/ISSUE_TEMPLATE/config.yml
  synthtool/gcp/templates/node_library/.github/ISSUE_TEMPLATE/feature_request.md
  synthtool/gcp/templates/node_library/.github/ISSUE_TEMPLATE/question.md
  synthtool/gcp/templates/node_library/.github/ISSUE_TEMPLATE/support_request.md
Labels: cla: yes

#1326 chore: add samples noxfile test
  noxfile.py
  requirements.txt
  synthtool/gcp/templates/python_samples/noxfile.py.j2
  tests/test_sample_templates.py
Labels: samples

#1331 chore(java): update release_type choices to stable and preview
  synthtool/gcp/templates/java_library/README.md
  tests/fixtures/java_templates/release-please-update/.repo-metadata.json
  tests/fixtures/java_templates/standard/.repo-metadata.json
Labels: automerge

#1332 chore(python): fix lint error in samples noxfile
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: samples

#1334 chore(python): Noxfile recognizes that tests can live in a folder
  synthtool/gcp/templates/python_samples/noxfile.py.j2
Labels: automerge

#1339 deps(java): update actions/github-script action to v5
  synthtool/gcp/templates/java_library/.github/workflows/approve-readme.yaml
  synthtool/gcp/templates/java_library/.github/workflows/auto-release.yaml
Labels: automerge
